environment:
  matrix:
    - nodejs_version: "12"
install:
  - cd express-postgres
  - ps: Install-Product node $env:nodejs_version
  - npm i
test_script:
  - npm test
build: off
before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb testdb
services:
  - postgresql101
