# GET https://localhost.project-melon-bread.com/v1/events

###
GET http://localhost:8081/v1/users

###

POST http://localhost:8081/v1/users/login
Content-Type: application/json

# {
#   "email": "m.yoshiosera@gmail.com"
# }
{
  "email": "mzawa@gmail.com"
}

###

GET http://localhost:8081/v1/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im0ueW9zaGlvc2VyYUBnbWFpbC5jb20iLCJpYXQiOjE2MTQ4MDAyNjl9.HxkV3J74VELM_WDGVzB-sVCxyAPOaN5GgsSli8Db7WY
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im16YXdhQGdtYWlsLmNvbSIsImlhdCI6MTYxNDgwMDY0Mn0.cN2ifKMGdqbKgawxWkNXrb0ndE95IIw8SnACqRRKJHc
